### ISSUE TITLE
na_summary should be able to specify columns to include or exclude

### ISSUE THREAD

**Issue by aalexandersson** [Nelson-Gon/mde#29]
**Description**

The function **`na_summary()`** should be able to specify a subset of columns to include or exclude.

**Similar Features**

This would enhance the `na_summary() function`. The `percent_missing()` function already has this feature in the argument `exclude_cols`. The argument `...` in the `na_summary()' function might have the feature but there is no documentation of example usage.

**Feature Details**

The documented usage is
`na_summary(df, grouping_cols = NULL, sort_by = NULL, descending = FALSE, ...)` 
where ... is Arguments to other functions.
But here `...` fails. That is, the `exclude_cols` argument, which is an argument to the `percent_missing()` function, fails with an error when used in the  `na_summary()` function. Here is an MWE:
```
> library(mde)
Welcome to mde. This is mde version 0.2.1.
 Please file issues and feedback at https://www.github.com/Nelson-Gon/mde/issues
Turn this message off using 'suppressPackageStartupMessages(library(mde))'
 Happy Exploration :)
> na_summary(airquality)
  variable missing complete percent_complete percent_missing
1      Day       0      153        100.00000        0.000000
2    Month       0      153        100.00000        0.000000
3    Ozone      37      116         75.81699       24.183007
4  Solar.R       7      146         95.42484        4.575163
5     Temp       0      153        100.00000        0.000000
6     Wind       0      153        100.00000        0.000000
> percent_missing(airquality, exclude_cols = c("Day","Temp"))
     Ozone  Solar.R Wind Month
1 24.18301 4.575163    0     0
> na_summary(airquality, exclude_cols = c("Day","Temp"))
Error in na_summary.data.frame(airquality, exclude_cols = c("Day", "Temp")) : 
  Binding of datasets failed. Please check using percent_missing and get_na_counts first
```

**Proposed Implementation**

I can think of at least four possible implementations:
A. Provide example documentation of how to use the argument `exclude_cols` of the `percent_missing()` function as the argument `...`  in the `na_summary()` function.
*or*
B. Add the argument `exclude_cols` or `include_cols` to the `na_summary()` function for variables you want to exclude or include.
*or*
C. Add a boolean argument for missingness versus completeness so that you will either get a completeness report (with the statistics columns `complete` and `percent_complete`) or a minimal missingness report (with the statistics columns `missing` and `percent_missing`).
*or*
D. Add the argument `exclude_stats` or `include_stats` to the `na_summary()` function for statistics you want to exclude or include.

I propose A. if the issue is only a matter of improving the documentation. Otherwise it is a feature request which can be implemented in several different ways such as B, C, or D.

**Comment by Nelson-Gon** [comment]
Hello,

Thank you for reporting this issue. I have taken a look and as of now `exclude_columns` has been explicitly added to `na_summary`. Option D is also interesting. This should be fully resolved later today.

Thank you very much once again,

Nelson

**Comment by aalexandersson** [comment]
Thank you!
Anders
